<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
  public function getProductListQuery($em){
    $dql = "SELECT p FROM AppBundle:Product p ORDER BY p.createTime DESC";
    $query = $em->createQuery($dql);
    return $query;
  }
  
  public function saveNewProduct($em, $product) {
    $now = new\DateTime('now');
    $product->setCreateTime($now);
    $em->persist($product);
    $em->flush();
  }
}
