AppBundle\Entity\Product:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255
                maxMessage: 'Product name cannot be longer than {{ limit }} characters'
        description:
            - NotBlank: ~
            - Length:
                min: 100
                minMessage: 'Product description must be at least {{ limit }} characters long'
        price:
            - NotBlank: ~
            - Regex:
                pattern: '/^([1-9][0-9]*|0)(\.[0-9]{2})?$/'
                match:   true
                message: 'Your price has invalid format'